### PR TITLE
Force close decision on limit exceeded during task processing

### LINKED ISSUE #966: Buffered Events Full Protection
Currently, when the buffered events exceeds 100, limit exceed error will be thrown, causing for example timer processing logic fail to add a usr timer fire event. Although there is a retry policy and retry count on the task processing logic, eventually the processing of task will cause the shard to close. 

The overall effect of this bug are but not limited to:
1. shard got stuck, ack level cannot move
2. workflows which are hosted in the same shard got stuck
3. task cannot be successfully cleaned up

Shard info:
```
cadence@cqlsh:cadence_autobots_prod_sjc1a> select shard from executions where shard_id = 5937 and type = 0 and domain_id = 10000000-1000-f000-f000-000000000000 and workflow_id = '20000000-1000-f000-f000-000000000000' and run_id = 30000000-1000-f000-f000-000000000000;

 shard
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 {shard_id: 5937, owner: '10.66.13.162:31187', range_id: 173, stolen_since_renew: 0, updated_at: '2018-07-16 16:50:22.839000+0000', transfer_ack_level: 181449894, timer_ack_level: '2018-07-13 17:17:32.536000+0000', replication_ack_level: 181447386, cluster_transfer_ack_level: {'autobots_prod_dca1a': 181449894, 'autobots_prod_sjc1a': 181449894}, cluster_timer_ack_level: {'autobots_prod_dca1a': '2018-07-16 16:44:19.067000+0000', 'autobots_prod_sjc1a': '2018-07-13 17:17:32.536000+0000'}, domain_notification_version: 56}

(1 rows)
```

Execution info
```
cadence@cqlsh:cadence_autobots_prod_sjc1a> select * from executions where type = 1 and domain_id = 1fcc0143-02d3-44a8-9adc-26c258b9c18c and workflow_id = 'd3ac3c24-efed-4996-963b-6456ed01e776' allow filtering;

 shard_id | type | domain_id                            | workflow_id                          | run_id                               | visibility_ts                   | task_id | activity_map | buffered_events_list                     | buffered_replication_tasks_map | child_executions_map | current_run_id                       | execution                                                                                                     | next_event_id | range_id | replication | replication_state                                                                                                           | request_cancel_map | shard | signal_map | signal_requested | timer | timer_map                                                                                                     | transfer
----------+------+--------------------------------------+--------------------------------------+--------------------------------------+---------------------------------+---------+--------------+------------------------------------------------+--------------------------------+----------------------+--------------------------------------+------------------------------------------------------------------------------------------------------+---------------+----------+-------------+--+--------------------+-------+------------+------------------+-------+---------------------------------------------------------------------------------------------------------------+----------
     5937 |    1 | 1fcc0143-02d3-44a8-9adc-26c258b9c18c | d3ac3c24-efed-4996-963b-6456ed01e776 | a6792678-a735-4362-83fa-6c51cefeb29d | 2000-01-01 00:00:00.000000+0000 |     -10 |         null | [{encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}, {encoding_type: 'json', version: 1, data: ****}] |                           null |                 null |                                 null | {domain_id: 1fcc0143-02d3-44a8-9adc-26c258b9c18c, workflow_id: 'd3ac3c24-efed-4996-963b-6456ed01e776', run_id: a6792678-a735-4362-83fa-6c51cefeb29d, parent_domain_id: 10000000-0000-f000-f000-000000000000, parent_workflow_id: '', parent_run_id: 30000000-0000-f000-f000-000000000000, initiated_id: -7, completion_event: null, task_list: 'goautobots-dsl-wf-task-list-7', workflow_type_name: 'AutobotsDSLWorkflow', decision_task_timeout: 30, execution_context: null, state: 1, close_status: 0, next_event_id: 2378, last_processed_event: 2372, start_time: '2018-07-06 17:17:33.285000+0000', last_updated_time: '2018-07-13 09:33:06.548000+0000', create_request_id: b19ad2aa-e84d-4069-bae1-dae78a5d166c, decision_schedule_id: 2376, decision_started_id: 2377, decision_request_id: 'request-from-RespondDecisionTaskCompleted', decision_timeout: 30, cancel_requested: False, cancel_request_id: '', workflow_timeout: 864000, sticky_task_list: 'compute2792-sjc1:de0d3fc8-4952-4d45-baf9-2d4142f96755', sticky_schedule_to_start_timeout: 5, decision_attempt: 0, decision_timestamp: 0, client_library_version: '0.7.0', client_feature_version: '1.0.0', client_impl: 'uber-go', last_first_event_id: 2373, decision_version: 1} |          2378 |     null |        null |           {current_version: 1, start_version: 1, last_write_version: 1, last_write_event_id: 2377, last_replication_info: {}} |               null |  null |       null |             null |  null | {'0': {timer_id: '0', started_id: 7, expiry_time: '2018-07-13 17:17:33.299000+0000', task_id: 1, version: 1}} |     null
     5937 |    1 | 1fcc0143-02d3-44a8-9adc-26c258b9c18c | d3ac3c24-efed-4996-963b-6456ed01e776 | 30000000-0000-f000-f000-000000000001 | 2000-01-01 00:00:00.000000+0000 |     -10 |         null |                                     null |                           null |                 null | a6792678-a735-4362-83fa-6c51cefeb29d |                                                                       {domain_id: null, workflow_id: null, run_id: a6792678-a735-4362-83fa-6c51cefeb29d, parent_domain_id: null, parent_workflow_id: null, parent_run_id: null, initiated_id: null, completion_event: null, task_list: null, workflow_type_name: null, decision_task_timeout: null, execution_context: null, state: 1, close_status: 0, next_event_id: null, last_processed_event: null, start_time: null, last_updated_time: null, create_request_id: b19ad2aa-e84d-4069-bae1-dae78a5d166c, decision_schedule_id: null, decision_started_id: null, decision_request_id: null, decision_timeout: null, cancel_requested: null, cancel_request_id: null, workflow_timeout: null, sticky_task_list: null, sticky_schedule_to_start_timeout: null, decision_attempt: null, decision_timestamp: null, client_library_version: null, client_feature_version: null, client_impl: null, last_first_event_id: null, decision_version: null} |          null |     null |        null | {current_version: null, start_version: 1, last_write_version: null, last_write_event_id: null, last_replication_info: null} |               null |  null |       null |             null |  null |                                                                                                          null |     null

(2 rows)
```

User timer which got stuck
```
{domain_id: 1fcc0143-02d3-44a8-9adc-26c258b9c18c, workflow_id: 'd3ac3c24-efed-4996-963b-6456ed01e776', run_id: a6792678-a735-4362-83fa-6c51cefeb29d, visibility_ts: '2018-07-13 17:17:33.299000+0000', task_id: 9437499, type: 2, timeout_type: 0, event_id: 7, schedule_attempt: 0, version: 1}
```

### PR DESCRIPTION
**Pull request by samarabbas**
Transfer/Timer task processing should force close any outstanding
decision if it cannot update execution state due to limit exceeded
error.

fixes #966

### CODE REVIEW

File: service/history/workflowExecutionContext.go [hunk 1]
```diff
@@ -430,3 +430,29 @@ func (c *workflowExecutionContext) updateWorkflowExecutionWithRetry(
 func (c *workflowExecutionContext) clear() {
 	c.msBuilder = nil
 }
+
+func (c *workflowExecutionContext) scheduleNewDecision(transferTasks []persistence.Task,
+	timerTasks []persistence.Task) ([]persistence.Task, []persistence.Task, error) {
+	msBuilder, err := c.loadWorkflowExecution()
+	if err != nil {
+		return transferTasks, timerTasks, err
```
Comment (wxing1292) [inline service/history/workflowExecutionContext.go]: nil, nil, err

Comment (wxing1292) [reply service/history/workflowExecutionContext.go]: i see the point that returning the input transfer task and timer task to caller, for convenience, however, this too some degree is surprising, since if the return err is not nil, other returned parameters should be considered invalid

File: service/history/transferQueueActiveProcessor.go [hunk 2]
```diff
@@ -1115,6 +1101,41 @@ Update_History_Loop:
...
+					// Generate a transaction ID for appending events to history
+					transactionID, err1 := t.historyService.shard.GetNextTransferTaskID()
+					if err1 != nil {
+						return err1
+					}
+					err1 = context.updateWorkflowExecution(transT, timerT, transactionID)
+					if err1 != nil {
+						return err1
+					}
+				}
```
Comment (wxing1292) [inline service/history/transferQueueActiveProcessor.go]: can we log an error if !ok ?

File: service/history/timerQueueActiveProcessor.go [hunk 3]
```diff
@@ -691,13 +684,51 @@ func (t *timerQueueActiveProcessorImpl) updateWorkflowExecution(
...
+				// Generate a transaction ID for appending events to history
+				transactionID, err1 := t.historyService.shard.GetNextTransferTaskID()
+				if err1 != nil {
+					return err1
+				}
+				err1 = context.updateWorkflowExecution(transT, timerT, transactionID)
+				if err1 != nil {
+					return err1
+				}
+			}
```
Comment (wxing1292) [inline service/history/timerQueueActiveProcessor.go]: can we log an error here is !ok

File: service/history/workflowExecutionContext.go (hunk 1 above)
Comment (samarabbas) [reply service/history/workflowExecutionContext.go]: Although returning nil for transfer and timer tasks makes sense but it will make the code even uglier.  The issue I need to return them in the first place is to accept a slice and append more tasks to it and return the new slice with appended values.  The pattern is to pass in a slice and then store the return arguments to the same slice.  Setting it to nil on error will result in corrupting the original slice unless I store the result in a temporary variable and them store back to original variable if the error is not nil.  I prefer to leave this as is unless you have other objections.

File: service/history/transferQueueActiveProcessor.go (hunk 2 above)
Comment (samarabbas) [reply service/history/transferQueueActiveProcessor.go]: General task processing logic already all errors resulting in failure of the task.

File: service/history/timerQueueActiveProcessor.go (hunk 3 above)
Comment (samarabbas) [reply service/history/timerQueueActiveProcessor.go]: General task processing logic already all errors resulting in failure of the task.

File: service/history/workflowExecutionContext.go (hunk 1 above)
Comment (wxing1292) [reply service/history/workflowExecutionContext.go]: please add some comments then, since this is not the common behavior usually seen in the code.

File: service/history/transferQueueActiveProcessor.go (hunk 2 above)
Comment (wxing1292) [reply service/history/transferQueueActiveProcessor.go]: nop, i mean this
```
if di, ok := msBuilder.GetInFlightDecisionTask(); ok {
    // some business logic
} else {
    // add some log here since this should be an impossible case 
}
```
