### PR TITLE
fix(matching): fix rate-limiter token waste and CPU spin under low task rates

### LINKED ISSUE #7976: Server-side task rate-limit skips intervals or completely makes not progress for fractional values of worker_activities_per_second
### Description
Cadence allows fractional worker_activities_per_second. For instance, worker_activities_per_second=0.167 expected to pass one activity every 6 seconds, but instead some (or most) workflows are not making progress at all.

### Steps to Reproduce / How to Trigger
Add the following config to the client' task-list configuration section:
```
options:
        task_list_activities_per_second: 0.167
```
Then start 10 hello-world workflows (with big enough ScheduleToStart timeouts).

### Expected Behavior
Workflows are finished every 6 seconds (they have only one activity): first workflow finished immediately, second one after 6 seconds, etc. All 10 workflows launched at the same time should succeed within 54 seconds.

### Actual Behavior
Actual behaviour is flaky. Sometimes multiple workflows succeed, but often it is just two - others are getting timed out. Every time you can notice some internals are skipped: first workflow finished immediately, then second finished in 12 seconds (not in 6), next one in 30 seconds (18s and 24s intervals are like "skipped").

### Logs / Screenshots
Image

### Environment
- **Cadence server version**: master:head
- **Cadence SDK language and version** (if applicable): Language and SDK version
- **Cadence web version** (if applicable): Web UI version
- **DB & version**: sqlite, but same happens with Cassandra
- **Scale**: 1 local instance of cadence-server

### PR DESCRIPTION
**Pull request by dkrotx**
----
fix(matching): fix dispatch timeout truncation causing skipped rate-limit intervals

Fixes #7976

**[What changed?]**
Fixed `getDispatchTimeout` in `task_reader.go` and added a `taskDispatchTimeoutBuffer`:

1. The timeout formula was `time.Duration(float64(N)/rps) * time.Second`. For
   rps=0.167 (1 task per ~6 s) and N=1 buffer this evaluates as:
     `time.Duration(5.988...) * time.Second`
   Casting 5.988 to `time.Duration` (int64) truncates it to 5,
   so the result was 5 s instead of the correct ~5.988 s. The fix moves the
   multiplication inside the float expression:
     `time.Duration(float64(N*time.Second) / rps)`
   which preserves sub-second precision correctly.

2. Even with the corrected formula the timeout equalled the rate-limiter period
   exactly, leaving no extra time for the actual dispatch after `Wait()` returned.
   A `taskDispatchTimeoutBuffer` of 100 ms is added so the dispatch context
   always has headroom after the rate-limit token is obtained.

**[Why?]**
With `task_list_activities_per_second=0.167` the dispatch context timed out at
exactly the moment the rate-limiter released a token. The token was already
spent but the subsequent `dispatchTask` call immediately saw a cancelled
context, so the interval was silently skipped. Workflows stalled or timed out
even though the rate-limiter was making forward progress internally.

**[How did you test it?]**
- Updated `TestGetDispatchTimeout` expectations to include `taskDispatchTimeoutBuffer`.

**[Potential risks]**
Core task-dispatch path change. The 100 ms buffer is small relative to any
realistic rate-limit period and is bounded by the task-list cancel context.

Signed-off-by: Jan Kisel <dkrot@uber.com>

### CODE REVIEW

File: service/matching/tasklist/task_reader.go [hunk 1]
```diff
@@ -452,6 +451,18 @@ func (tr *taskReader) dispatchSingleTaskFromBufferWithRetries(taskInfo *persiste
 	}
 }
 
+func (tr *taskReader) waitForRetry() {
+	timer := tr.timeSource.NewTimer(time.Second)
```
Comment (natemort) [inline service/matching/tasklist/task_reader.go]: Nit: TimeSource.SleepWithContext turns this into a one liner.

**Review by natemort — APPROVED** [review]
