### PR TITLE
fix(history): prevent signals from bypassing DelayStart

### LINKED ISSUE #7595: Signals Override DelayStart
**Version of Cadence server, and client(which language)**
This is very important to root cause bugs.
- Server version: 1.3.7-prerelease27, but pretty much every version
- Client version: Any
- Client langauge: Any

**Describe the bug**
Workflows may be started with a DelayStart, which allows their execution to begin at a specified offset. This works by creating a timer task and then dispatching the first decision task at that later point in time.

If a workflow is Signaled prior to that time it will dispatch a decision task early, causing the DelayStart not to be respected.

**To Reproduce**
Is the issue reproducible? 
- Yes

**Steps to reproduce the behavior:**
- Start a Workflow using DelayStart.
- Prior to the DelayStart expiring, Signal the workflow.
- Observe that the first decision task was dispatched sooner than the DelayStart.

**Expected behavior**
A decision task should not be dispatched prior to the DelayStart, regardless of signals.

**Additional context**
We need to adjust the logic [here](https://github.com/cadence-workflow/cadence/blob/399ed85406257690010f9e47609305c663d2f1aa/service/history/engine/engineimpl/signal_workflow_execution.go#L90). Currently it considers cron workflows that haven't processed a decision task.

I believe the correct solution is to not schedule a decision task any time the workflow hasn't processed a decision task, as that indicates it is waiting for an external condition (cron or delay start).

We should be able to add an integration test for this by starting a Workflow with a very large delay start, signaling it, and then calling `DescribeWorkflowExecution` to check for a pending decision.

This change in behavior should be behind a feature flag.

### PR DESCRIPTION
**Pull request by pratikscfr**
**What changed?**
Fixes #7595 by removing the SignalDelayStart protection flag and making the “don’t schedule the first decision” logic unconditional for both SignalWorkflowExecution and SignalWithStart. Strengthened coverage by asserting DecisionScheduleID stays commonconstants. EmptyEventID in the engine unit test while keeping the host integration test.

**Why?**
Issue #7595 describes that a workflow waiting on DelayStart (or its first Cron decision) should remain idle even if it receives signals—otherwise the signal immediately schedules a decision and the workflow starts early. Both the regular signal path and SignalWithStart were still creating that decision, so DelayStart was effectively bypassed. This change makes the protection unconditional (matching the issue’s request) so signals now behave the same as the normal start path and DelayStart/Cron timers are honored.

**How did you test it?**
go test ./service/history/engine/engineimpl -count=1  
go test ./host -run TestIntegrationSuite -testify.m TestSignalDoesNotOverrideDelayStart -count=1  

Manual steps (SQLite):
1. ./cadence-server --zone sqlite start  
2. ./bin/helloworld -m worker  
3. ./cadence --do cadence-samples workflow start \
     --workflow_id delay-signal-demo-4 \
     --tasklist helloWorldGroup \
     --workflow_type helloWorldWorkflow \
     --execution_timeout 60 \
     --decision_timeout 60 \
     --delay_start_seconds 300 \
     --input '"Cadence"'  
4. ./cadence --do cadence-samples workflow signal \
     --workflow_id delay-signal-demo-4 \
     --name test-signal \
     --input '"payload"'  
5. ./cadence --do cadence-samples workflow describe \
     --workflow_id delay-signal-demo-4  
   (Confirmed CloseStatus=null and PendingDecision=null while DelayStart timer was running.)

**Potential risks**
Low—only affects decision scheduling before the first decision task, no schema or API changes.

**Release notes**
Signals sent before a workflow’s first decision no longer schedule a decision task while DelayStart/Cron is pending (Fixes #7595).

**Documentation Changes**
N/A – DelayStart behavior now matches the expectation from issue #7595 (signals no longer wake the workflow early), so no docs need changes.

### CODE REVIEW

**Review by Shaddoll — APPROVED** [review]

File: service/history/engine/engineimpl/signal_workflow_execution.go [hunk 1]
```diff
@@ -86,8 +86,7 @@ func (e *historyEngineImpl) SignalWorkflowExecution(
 
 			executionInfo := mutableState.GetExecutionInfo()
 			createDecisionTask := true
-			// Do not create decision task when the workflow is cron and the cron has not been started yet
-			if mutableState.GetExecutionInfo().CronSchedule != "" && !mutableState.HasProcessedOrPendingDecision() {
+			if !mutableState.HasProcessedOrPendingDecision() {
```
Comment (Shaddoll) [inline service/history/engine/engineimpl/signal_workflow_execution.go:89]: nit: could you add a comment saying that this is for cron and delay start workflows?
