### PR TITLE
Workflow retry incorrectly set attempt on start event of new run

### LINKED ISSUE #1485: Workflow server side retry ignores RetryOptions.maxAttempts
I was able to reproduce the problem using both Java and Go clients. The issue is that `WorkflowExecutionStarted.Attemp `field is not incremented beyond value of 2 on each continue as new and workflow is retried ignoring `maxAttempts` because of that. 

I reproduced with the following docker releases:

```
    image: ubercadence/server:0.5.2
    image: ubercadence/server:0.5.1

```
Here are histories from one of my tests:

```
  1  WorkflowExecutionStarted         (WorkflowType:(Name:SampleChildWorkflow), ParentWorkflowDomain:samples-domain,
                                       ParentWorkflowExecution:(WorkflowId:parentworkflow_3ef3aa10-e854-4289-8243-e238a413f54b,
                                       RunId:a5c6abe6-eaaa-4df6-8771-872c024cc4af), ParentInitiatedEventId:5,
                                       TaskList:(Name:cadence-samples-tasklist), Input:[0 5],
                                       ExecutionStartToCloseTimeoutSeconds:20, TaskStartToCloseTimeoutSeconds:10,
                                       ContinuedExecutionRunId:343c25d2-66cf-477d-8694-0d04ee9f09ae, Initiator:RetryPolicy,
                                       ContinuedFailureReason:cadenceInternal:Generic, ContinuedFailureDetails:[simulated],
                                       LastCompletionResult:[], RetryPolicy:(InitialIntervalInSeconds:1, BackoffCoefficient:1,
                                       MaximumIntervalInSeconds:100, MaximumAttempts:3, NonRetriableErrorReasons:[len=0],
                                       ExpirationIntervalInSeconds:3600), Attempt:2, FirstDecisionTaskBackoffSeconds:1)
  2  DecisionTaskScheduled            (TaskList:(Name:cadence-samples-tasklist),
                                       StartToCloseTimeoutSeconds:10, Attempt:0)
  3  DecisionTaskStarted              (ScheduledEventId:2,
                                       Identity:11535@maxim-C02XD0AAJGH6@cadence-samples-tasklist,
                                       RequestId:fec15a15-345e-4591-bb41-8e46bc0c5161)
  4  DecisionTaskCompleted            (ExecutionContext:[], ScheduledEventId:2, StartedEventId:3,
                                       Identity:11535@maxim-C02XD0AAJGH6@cadence-samples-tasklist)
  5  WorkflowExecutionContinuedAsNew  (NewExecutionRunId:8a913c40-7887-495b-b8e3-0d9d77f05cea,
                                       WorkflowType:(Name:SampleChildWorkflow),
                                       TaskList:(Name:cadence-samples-tasklist), Input:[0
                                       5], ExecutionStartToCloseTimeoutSeconds:20,
                                       TaskStartToCloseTimeoutSeconds:10,
                                       DecisionTaskCompletedEventId:4,
                                       BackoffStartIntervalInSeconds:1, Initiator:RetryPolicy,
                                       FailureReason:cadenceInternal:Generic,
                                       FailureDetails:[simulated], LastCompletionResult:[])

uber-java-cadence-client: cadence -do samples-domain workflow show --wid child_workflow:a5c6abe6-eaaa-4df6-8771-872c024cc4af --rid 8a913c40-7887-495b-b8e3-0d9d77f05cea
  1  WorkflowExecutionStarted         (WorkflowType:(Name:SampleChildWorkflow), ParentWorkflowDomain:samples-domain,
                                       ParentWorkflowExecution:(WorkflowId:parentworkflow_3ef3aa10-e854-4289-8243-e238a413f54b,
                                       RunId:a5c6abe6-eaaa-4df6-8771-872c024cc4af), ParentInitiatedEventId:5,
                                       TaskList:(Name:cadence-samples-tasklist), Input:[0 5],
                                       ExecutionStartToCloseTimeoutSeconds:20, TaskStartToCloseTimeoutSeconds:10,
                                       ContinuedExecutionRunId:3ce3eb82-52e5-4a5a-b57f-f1561bc51136, Initiator:RetryPolicy,
                                       ContinuedFailureReason:cadenceInternal:Generic, ContinuedFailureDetails:[simulated],
                                       LastCompletionResult:[], RetryPolicy:(InitialIntervalInSeconds:1, BackoffCoefficient:1,
                                       MaximumIntervalInSeconds:100, MaximumAttempts:3, NonRetriableErrorReasons:[len=0],
                                       ExpirationIntervalInSeconds:3600), Attempt:2, FirstDecisionTaskBackoffSeconds:1)
  2  DecisionTaskScheduled            (TaskList:(Name:cadence-samples-tasklist),
                                       StartToCloseTimeoutSeconds:10, Attempt:0)
  3  DecisionTaskStarted              (ScheduledEventId:2,
                                       Identity:11535@maxim-C02XD0AAJGH6@cadence-samples-tasklist,
                                       RequestId:1b481994-e49f-484f-b089-0cf1f726572b)
  4  DecisionTaskCompleted            (ExecutionContext:[], ScheduledEventId:2, StartedEventId:3,
                                       Identity:11535@maxim-C02XD0AAJGH6@cadence-samples-tasklist)
  5  WorkflowExecutionContinuedAsNew  (NewExecutionRunId:c0b3d1c8-4a80-46cb-8ca3-f2898c0e8725,
                                       WorkflowType:(Name:SampleChildWorkflow),
                                       TaskList:(Name:cadence-samples-tasklist), Input:[0
                                       5], ExecutionStartToCloseTimeoutSeconds:20,
                                       TaskStartToCloseTimeoutSeconds:10,
                                       DecisionTaskCompletedEventId:4,
                                       BackoffStartIntervalInSeconds:1, Initiator:RetryPolicy,
                                       FailureReason:cadenceInternal:Generic,
                                       FailureDetails:[simulated], LastCompletionResult:[])
uber-java-cadence-client:
```
The code that reproduces the problem (modified childworkflow sample):

```
func SampleParentWorkflow(ctx workflow.Context) error {
	logger := workflow.GetLogger(ctx)
	execution := workflow.GetInfo(ctx).WorkflowExecution
	// Parent workflow can choose to specify it's own ID for child execution.  Make sure they are unique for each execution.
	childID := fmt.Sprintf("child_workflow:%v", execution.RunID)
	retryPolicy := &cadence.RetryPolicy {
		BackoffCoefficient:1,
		MaximumAttempts:3,
		ExpirationInterval:time.Hour,
		InitialInterval:time.Second,
	}
	cwo := workflow.ChildWorkflowOptions{
		// Do not specify WorkflowID if you want cadence to generate a unique ID for child execution
		WorkflowID:                   childID,
		ExecutionStartToCloseTimeout: time.Second * 20,
		RetryPolicy: retryPolicy,
	}
	ctx = workflow.WithChildOptions(ctx, cwo)
	var result string
	err := workflow.ExecuteChildWorkflow(ctx, sampleChildWorkflowName, 0, 5).Get(ctx, &result)
	if err != nil {
		logger.Error("Parent execution received child execution failure.", zap.Error(err))
		return err
	}

	logger.Info("Parent execution completed.", zap.String("Result", result))
	return nil
}

// SampleChildWorkflow workflow decider
func SampleChildWorkflow(ctx workflow.Context, totalCount, runCount int) (string, error) {
	return "", errors.New("simulated")
}

```

### PR DESCRIPTION
**Pull request by samarabbas**
Workflow execution with retry policy does not update attempt on
new run and always sets it to 1.  This results in retry policy to
never fail the execution based on attempt.  Fixing the mutablestate
update to use correct value for attempt from the new start
attributes.
Also added integration tests to validate attemp on start attributes
and also test bailout using attempt or non-retryable errors from
the policy.

fixes #1485

### CODE REVIEW

File: host/integration_test.go [hunk 1]
```diff
@@ -1019,7 +1019,7 @@ func (s *integrationSuite) TestWorkflowRetry() {
 		previousStartedEventID, startedEventID int64, history *workflow.History) ([]byte, []*workflow.Decision, error) {
 		executions = append(executions, execution)
 		attemptCount++
-		if attemptCount == 3 {
```
Comment (yiminc) [inline host/integration_test.go]: why is this not catching that attempt issue?

Comment (samarabbas) [reply host/integration_test.go]: The issue is workflow goes into an endless retry mode.  So attempt incremented within the workflow will reach 3.  The bugfix is to bailout the workflow due to hitting max attempts for retry policy.
