### PR TITLE
fix: Apply context timeout to appendTask and related call paths

### LINKED ISSUE #7642: Update AddTask method to respect context timeout
Use this template for feature, improvement, or refactoring requests.

### Description
The AddTask method doesn't respect context timeout in some places.
For example, the appendTask method doesn't accept context as a parameter, and the context could expire while it's waiting for this [select](https://github.com/cadence-workflow/cadence/blob/master/service/matching/tasklist/task_writer.go#L137) block. Besides, the context could expire while matcher is waiting for this [channel](https://github.com/cadence-workflow/cadence/blob/master/service/matching/tasklist/matcher.go#L173).

### Is this a breaking change?
- [ ] Yes
- [x] No

### Scope of the feature (server, specific client, all clients)
cadence-matching

Please resolve this [issue](https://github.com/cadence-workflow/cadence/issues/7641) first

### PR DESCRIPTION
**Pull request by Scanf-s**
**What changed?**
- [x] Added a child context with context.WithTimeout() so AddTask/appendTask can respect request timeout/cancellation.
- [x] Updated appendTask signature to accept context.Context and refactored all related call sites.
- [x] Changed the response channel to a buffer size of 1 to avoid writer-loop blocking when appendTask returns early on timeout while the write loop is still running.

**Why?**
- [x] Resolves #7642

**How did you test it?**
- [x] Ran `go test ./service/matching/tasklist` and succeeded
image

**Potential risks**

1. Refactored `appendTask` function now respects the timeout, but DB write tasks in taskWriterLoop function still use background context. I think, if timeout happened after enqueue the writeTask, the task may still be written to the database, which creates a duplicate task. But duplicate tasks is handled.

2. I set timeout value to 5 seconds but I’m not sure this is the right value yet.

**Release notes**

**Documentation Changes**

---

## Reviewer Validation

**PR Description Quality** (check these before reviewing code):

- [x] **"What changed"** provides a clear 1-2 line summary
  - [x] Project Issue is linked
- [x] **"Why"** explains the full motivation with sufficient context
- [x] **Testing is documented:**
  - [x] Unit test commands are included (with exact `go test` invocation)
  - [ ] Integration test setup/commands included (if integration tests were run)
  - [ ] Canary testing details included (if canary was mentioned)
- [x] **Potential risks** section is thoughtfully filled out (or legitimately N/A)
- [x] **Release notes** included if this completes a user-facing feature
- [x] **Documentation** needs are addressed (or noted if uncertain)

### CODE REVIEW

**Comment by Scanf-s** [comment]
I'll apply code review bot's suggestions and seek how to add `AppendTaskTimeout` in `config.TaskListConfig`

File: service/matching/tasklist/task_writer.go [hunk 1]
```diff
@@ -121,27 +121,36 @@ func (w *taskWriter) isStopped() bool {
...
+		case <-ctx.Done(): // If the writer didn't send the task result within a timeout threshold
+			return nil, ctx.Err()
 		case <-w.stopCh:
 			// if we are shutting down, this request will never make
 			// it to cassandra, just bail out and fail this request
 			return nil, errShutdown
 		}
+	case <-ctx.Done(): // If enqueue failed due to context timeout
+		return nil, ctx.Err()
 	default: // channel is full, throttle
```
Comment (Shaddoll) [inline service/matching/tasklist/task_writer.go]: I think the default branch should be removed.

File: service/matching/tasklist/task_writer.go [hunk 2]
```diff
@@ -121,27 +121,36 @@ func (w *taskWriter) isStopped() bool {
...
-	case w.appendCh <- req:
-		select {
-		case r := <-ch:
+	select { // Try to append a task into the queue
+	case w.appendCh <- req: // If enqueue succeed
+		select { // Wait for the task result after the enqueue
+		case r := <-ch: // If the writer sends the task result after the DB I/O task
 			return r.persistenceResponse, r.err
+		case <-ctx.Done(): // If the writer didn't send the task result within a timeout threshold
+			return nil, ctx.Err()
```
Comment (Shaddoll) [inline service/matching/tasklist/task_writer.go]: Could you wrap this error with a message indicating that the timeout is because the response is not sent back?

File: service/matching/tasklist/task_writer.go [hunk 3]
```diff
@@ -121,27 +121,36 @@ func (w *taskWriter) isStopped() bool {
...
 		case <-w.stopCh:
 			// if we are shutting down, this request will never make
 			// it to cassandra, just bail out and fail this request
 			return nil, errShutdown
 		}
+	case <-ctx.Done(): // If enqueue failed due to context timeout
+		return nil, ctx.Err()
```
Comment (Shaddoll) [inline service/matching/tasklist/task_writer.go]: Could you wrap this error with a message indicating that the timeout is because it failed to append a task into the queue?

File: service/matching/tasklist/task_list_manager.go [hunk 4]
```diff
@@ -531,6 +531,10 @@ func (c *taskListManagerImpl) notifyPartitionConfig(ctx context.Context, oldConf
 func (c *taskListManagerImpl) AddTask(ctx context.Context, params AddTaskParams) (bool, error) {
 	c.startWG.Wait()
 
+	// Make context to respect the append task timeout.
+	tCtx, cancel := context.WithTimeout(ctx, c.config.AppendTaskTimeout())
```
Comment (Shaddoll) [inline service/matching/tasklist/task_list_manager.go]: I think you can move this logic inside the appendTask method to decrease duplicate code.
