### PR TITLE
Fix the incorrect error message output of the command `cadence workflow start/run`

### LINKED ISSUE #6726: CLI start workflow help command retry flags default values is incorrect
### Description
Trying to run the following cadence cli command:
```
cadence  --domain my-domain workflow start --tl helloWorldGroup --wt helloWorldWorkflow --et 60 --retry_attempts 0
``` 
Shows the following error:
```
MaximumAttempts and ExpirationIntervalInSeconds are both 0. At least one of them must be specified.
```

There are two things that made this message unclear:
1- It wasn't clear that the flag for `ExpirationIntervalInSeconds` is `--retry_expiration`
2- Second issue is that the help command mentioned that the default value for  `retry_attempts` is `0`  & `retry_expiration` is `0` which may not be the case since it would show this error by default

### Expected behaviour
A more descriptive error is need describing the exact flags on the CLI. Also the default value needs to be corrected or a correct description for when it is defaulted to 0 is needed.

### PR DESCRIPTION
**Pull request by ins-tril**
**Why?**
Fixes #6726 

**What changed?**
- Fix the incorrect error message output of the command `cadence workflow start/run`.
- Improve the usage message of `cadence workflow start/run`.

**How did you test it?**
unit tests, local functional tests

**Potential risks**

**Release notes**

**Documentation Changes**

### CODE REVIEW

File: tools/cli/flags.go [hunk 1]
```diff
@@ -426,7 +426,7 @@ func getFlagsForStart() []cli.Flag {
 		&cli.Float64Flag{
 			Name:  FlagRetryBackoff,
 			Value: 1.0,
-			Usage: "Optional retry backoff coeficient. Must be or equal or greater than 1.",
+			Usage: "Optional retry backoff coefficient. Must be or equal or greater than 1.",
```
Comment (ins-tril) [inline tools/cli/flags.go:429]: typo error.

File: tools/cli/workflow_commands_test.go [hunk 2]
```diff
@@ -2088,6 +2088,126 @@ func Test_NewTest(t *testing.T) {
...
+	}
+}
+
+func testStartWorkflowHelper(t *testing.T, shouldPrintProgress bool, tc struct {
+	cliArguments          []clitest.CliArgument
+	respondedErrorMessage string
+	expectedErrorMessage  string
+}) {
+	ctrl := gomock.NewController(t)
+	defer ctrl.Finish()
```
Comment (jakobht) [inline tools/cli/workflow_commands_test.go]: This is not needed any longer in gomock

File: tools/cli/workflow_commands_test.go [hunk 3]
```diff
@@ -2088,6 +2088,126 @@ func Test_NewTest(t *testing.T) {
...
+		},
+	}
+
+	for _, tc := range tests {
+		t.Run(tc.expectedErrorMessage, func(t *testing.T) {
+			err := replaceRetryPropertiesInErrorMessageWithRetryArguments(errors.New(tc.originalErrorMessage))
+			assert.Equal(t, tc.expectedErrorMessage, err.Error())
+		})
+	}
+}
```
Comment (jakobht) [inline tools/cli/workflow_commands_test.go]: This test is testing the same, but less as the one below, lets not have this test.

File: tools/cli/workflow_commands_test.go [hunk 4]
```diff
@@ -2088,6 +2088,126 @@ func Test_NewTest(t *testing.T) {
...
+
+func Test_StartWorkflowHelper_WithRetryArguments(t *testing.T) {
```
Comment (jakobht) [inline tools/cli/workflow_commands_test.go]:
```suggestion
func Test_StartWorkflowHelper_RetryErrorMapping(t *testing.T) {
```
We are only testing the errors, so lets reflect that in the name

File: tools/cli/workflow_commands_test.go [hunk 5]
```diff
@@ -2088,6 +2088,126 @@ func Test_NewTest(t *testing.T) {
...
+			append(requiredArguments, clitest.IntArgument(FlagRetryAttempts, 0), clitest.IntArgument(FlagRetryBackoff, 0)),
+			"MaximumAttempts and ExpirationIntervalInSeconds are both 0. At least one of them must be specified.",
+			"retry_attempts and retry_expiration are both 0. At least one of them must be specified.",
+		},
+	}
+
+	for _, tc := range tests {
+		t.Run(tc.expectedErrorMessage, func(t *testing.T) {
+			testStartWorkflowHelper(t, false, tc)
+			testStartWorkflowHelper(t, true, tc)
```
Comment (jakobht) [inline tools/cli/workflow_commands_test.go]: We can just test the `false` case here since we are just testing the error mappings. Then we can also drop having the `testStartWorkflowHelper` function and just inline it's code here.

**Comment by jakobht** [comment]
I see CI failed it looks like a problem with the infra, not your code, I'll see if I can rerun when the others have finished

File: tools/cli/workflow_commands_test.go (hunk 2 above)
Comment (ins-tril) [reply tools/cli/workflow_commands_test.go]: @jakobht Addressed.

File: tools/cli/workflow_commands_test.go (hunk 3 above)
Comment (ins-tril) [reply tools/cli/workflow_commands_test.go]: @jakobht Removed the test.

File: tools/cli/workflow_commands_test.go (hunk 4 above)
Comment (ins-tril) [reply tools/cli/workflow_commands_test.go]: @jakobht Renamed the test function.

File: tools/cli/workflow_commands_test.go (hunk 5 above)
Comment (ins-tril) [reply tools/cli/workflow_commands_test.go]: @jakobht Addressed.

**Review by jakobht — APPROVED** [review]
