### PR TITLE
Decision task failure support

### LINKED ISSUE #117: Explicit decision failure
The only way we support failing the decision is DecisionTimeout.  It may make sense in certain cases where we can explicitly nack a decision so it is picked up by another decider for faster processing instead of waiting for the decision timeout.

### PR DESCRIPTION
**Pull request by samarabbas**
Add API on Cadence frontend to support DecisionTaskFailure.  Added two new 
causes: RESET_STICKY_TASKLIST and WORKFLOW_WORKER_UNHANDLED_FAILURE
to support scenario of shedding load by clearing sticky tasklist and decider
failures during execution respectively.
Only first DecisionTaskFailure is reported in history and all subsequent retries are 
done using state from mutable state.  Mutable state keeps track of decision_attempt
and decision_timestamp and creates transient decisions while dispatching 
these decision tasks.  These transition decisions are stored in the history
and frontend has logic to deliver these events when it is done paginating through
all the events from history.
New schema changes to support transient decisions on mutable state.

Fixes #117 and #118 .

### CODE REVIEW

File: service/history/mutableStateBuilder.go [hunk 1]
```diff
@@ -699,82 +731,143 @@ func (e *mutableStateBuilder) AddWorkflowExecutionStartedEvent(domainID string,
...
+	}
+	e.UpdateDecision(di)
 
-	return event
+	return event, di
+}
+
+func (e *mutableStateBuilder) createTransientDecisionEvents(di *decisionInfo, identity string) (*workflow.HistoryEvent,
+	*workflow.HistoryEvent) {
+	tasklist := e.executionInfo.TaskList
```
Comment (yiminc) [inline service/history/mutableStateBuilder.go]: do you need to consider sticky task list here? you might not need to since you already clear sticky when failure happen.

File: common/persistence/cassandraPersistence.go [hunk 2]
```diff
@@ -1678,13 +1685,15 @@ func (d *cassandraPersistence) createTimerTasks(batch *gocql.Batch, timerTasks [
...
 		var eventID int64
+		var attempt int64
 
 		timeoutType := 0
 
 		switch task.GetType() {
 		case TaskTypeDecisionTimeout:
 			eventID = task.(*DecisionTimeoutTask).EventID
 			timeoutType = task.(*DecisionTimeoutTask).TimeoutType
+			attempt = task.(*DecisionTimeoutTask).ScheduleAttempt
```
Comment (mfateev) [inline common/persistence/cassandraPersistence.go]: Wouldn't it be cleaner to introduce a local variable to avoid all these casts?

File: idl/github.com/uber/cadence/shared.thrift [hunk 3]
```diff
@@ -135,6 +135,8 @@ enum DecisionTaskFailedCause {
   BAD_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_ATTRIBUTES,
   BAD_CONTINUE_AS_NEW_ATTRIBUTES,
   START_TIMER_DUPLICATE_ID,
+  RESET_STICKY_TASKLIST,
+  PANIC
```
Comment (mfateev) [inline idl/github.com/uber/cadence/shared.thrift]: Panic is go specific. I would rename to Failure

File: idl/github.com/uber/cadence/matching.thrift [hunk 4]
```diff
@@ -34,8 +34,10 @@ struct PollForDecisionTaskResponse {
   30: optional shared.WorkflowType workflowType
   40: optional i64 (js.type = "Long") previousStartedEventId
   50: optional i64 (js.type = "Long") startedEventId
-  55: optional bool stickyExecutionEnabled
-  60: optional shared.WorkflowQuery query
+  60: optional i64 (js.type = "Long") nextEventId
```
[the remark this answers is not in the document]
Comment (samarabbas) [reply idl/github.com/uber/cadence/matching.thrift]: This is only for matching service and we upgrade the entire service during rollout.  That's why I updated the field as we will be upgrading fe and matching at the same time.

File: idl/github.com/uber/cadence/shared.thrift (hunk 3 above)
[the remark this answers is not in the document]
Comment (samarabbas) [reply idl/github.com/uber/cadence/shared.thrift]: Done.

File: service/frontend/handler.go [hunk 5]
```diff
@@ -391,7 +392,7 @@ func (wh *WorkflowHandler) PollForDecisionTask(
 	var continuation []byte
 	if matchingResp.WorkflowExecution != nil {
 		// Non-empty response. Get the history
-		nextEventID := common.Int64Default(matchingResp.StartedEventId) + 1
+		nextEventID := matchingResp.GetNextEventId()
```
[the remark this answers is not in the document]
Comment (samarabbas) [reply service/frontend/handler.go]: Yes.  That is correct.  NextEventID is used to send query down to events table and Schedule/Start events are included in the token until we are done enumerating over the events table.

File: service/history/mutableStateBuilder.go (hunk 1 above)
Comment (samarabbas) [reply service/history/mutableStateBuilder.go]: Currently I have simplified the state machine to clear sticky tasklist on each failure.  Otherwise you are right we need additional in mutable state to remember that too.
Let's keep it simple until there is a need to remember tasklist also for failed decisions.

File: service/history/mutableStateBuilder.go [hunk 6]
```diff
@@ -786,27 +879,35 @@ func (e *mutableStateBuilder) AddDecisionTaskScheduleToStartTimeoutEvent(schedul
...
 		logging.LogInvalidHistoryActionEvent(e.logger, logging.TagValueActionDecisionTaskFailed, e.GetNextEventID(), fmt.Sprintf(
 			"{HasPending: %v, ScheduleID: %v, StartedID: %v, Exist: %v}", hasPendingDecision, scheduleEventID,
 			startedEventID, ok))
 		return nil
 	}
 
-	event := e.hBuilder.AddDecisionTaskFailedEvent(scheduleEventID, startedEventID, cause, request)
+	var event *workflow.HistoryEvent
+	// Only emit DecisionTaskFailedEvent for the very first time
+	if dt.Attempt == 0 {
```
[the remark this answers is not in the document]
Comment (samarabbas) [reply service/history/mutableStateBuilder.go]: I'm little confused.  We do keep track of continuous failure count and include that as part of the DecisionTaskScheduledEvent

File: common/persistence/cassandraPersistence.go (hunk 2 above)
Comment (samarabbas) [reply common/persistence/cassandraPersistence.go]: Done.

File: idl/github.com/uber/cadence/cadence.thrift [hunk 7]
```diff
@@ -130,6 +130,18 @@ service WorkflowService {
       3: shared.EntityNotExistsError entityNotExistError,
     )
 
+  /**
+  * RespondDecisionTaskFailed is called by application worker to indicate failure.  This results in
+  * DecisionTaskFailedEvent written to the history and a new DecisionTask created.  This API can be used by client to
```
[the remark this answers is not in the document]
Comment (samarabbas) [reply idl/github.com/uber/cadence/cadence.thrift]: Done.

File: idl/github.com/uber/cadence/shared.thrift [hunk 8]
```diff
@@ -136,7 +136,7 @@ enum DecisionTaskFailedCause {
   BAD_CONTINUE_AS_NEW_ATTRIBUTES,
   START_TIMER_DUPLICATE_ID,
   RESET_STICKY_TASKLIST,
-  PANIC
+  DECIDER_PANIC
```
Comment (mfateev) [inline idl/github.com/uber/cadence/shared.thrift]: Panic is golang specific. I would change it to WORKFLOW_WORKER_UNHANDLED_FAILURE.
